export const FEED_LOADED = "FEED_LOADED";
export const USER_PAGE_LOADED = "USER_PAGE_LOADED";
export const CHATS_LOADED = "CHATS_LOADED";
export const CHAT_LOADED = "CHAT_LOADED";
export const FOLLOWED_LOADED = "FOLLOWED_LOADED";
export const FOLLOWING_LOADED = "FOLLOWING_LOADED";
export const LIKED_LOADED = "LIKED_LOADED";